/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;

import controlador.ControladorRequerimientos;


/**
 *
 * @author GAME
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    private final VentanaLideres ventanaLideres;
    private final VentanaMateriales ventanaMateriales;
    private final VentanaPromedio ventanaPromedio;
    
    
    
    public VentanaPrincipal() {
        initComponents();
        ventanaLideres = new VentanaLideres();
        ventanaLideres.setVisible(false);
        
        ventanaMateriales = new VentanaMateriales();
        ventanaMateriales.setVisible(false);
        
        ventanaPromedio = new VentanaPromedio();
        ventanaPromedio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BotonConsulta1 = new javax.swing.JPanel();
        LabelConsulta1 = new javax.swing.JLabel();
        BotonConsulta2 = new javax.swing.JPanel();
        LabelConsulta2 = new javax.swing.JLabel();
        BotonConsulta3 = new javax.swing.JPanel();
        LabelConsulta3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\GAME\\Desktop\\El gordo\\Logos\\UTP Name.gif")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 60, 300, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\GAME\\Desktop\\El gordo\\Logos\\Name.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 470, 290));

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RETO 5");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 100));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("INICIO");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 160, 50));

        BotonConsulta1.setBackground(new java.awt.Color(255, 153, 153));
        BotonConsulta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        BotonConsulta1.setForeground(new java.awt.Color(255, 255, 255));

        LabelConsulta1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        LabelConsulta1.setForeground(new java.awt.Color(0, 0, 255));
        LabelConsulta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsulta1.setText("CONSULTA 1");
        LabelConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelConsulta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelConsulta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelConsulta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelConsulta1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonConsulta1Layout = new javax.swing.GroupLayout(BotonConsulta1);
        BotonConsulta1.setLayout(BotonConsulta1Layout);
        BotonConsulta1Layout.setHorizontalGroup(
            BotonConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        BotonConsulta1Layout.setVerticalGroup(
            BotonConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jPanel2.add(BotonConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 310, 100));

        BotonConsulta2.setBackground(new java.awt.Color(255, 153, 153));
        BotonConsulta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 0, 0), 3));
        BotonConsulta2.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsulta2.setPreferredSize(new java.awt.Dimension(300, 100));

        LabelConsulta2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        LabelConsulta2.setForeground(new java.awt.Color(0, 0, 255));
        LabelConsulta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsulta2.setText("CONSULTA 2");
        LabelConsulta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelConsulta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelConsulta2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelConsulta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelConsulta2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonConsulta2Layout = new javax.swing.GroupLayout(BotonConsulta2);
        BotonConsulta2.setLayout(BotonConsulta2Layout);
        BotonConsulta2Layout.setHorizontalGroup(
            BotonConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        BotonConsulta2Layout.setVerticalGroup(
            BotonConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jPanel2.add(BotonConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 310, 100));

        BotonConsulta3.setBackground(new java.awt.Color(255, 153, 153));
        BotonConsulta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 0, 0), 3));
        BotonConsulta3.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsulta3.setPreferredSize(new java.awt.Dimension(300, 100));

        LabelConsulta3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        LabelConsulta3.setForeground(new java.awt.Color(0, 0, 255));
        LabelConsulta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsulta3.setText("CONSULTA 3");
        LabelConsulta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelConsulta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelConsulta3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelConsulta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelConsulta3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonConsulta3Layout = new javax.swing.GroupLayout(BotonConsulta3);
        BotonConsulta3.setLayout(BotonConsulta3Layout);
        BotonConsulta3Layout.setHorizontalGroup(
            BotonConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        BotonConsulta3Layout.setVerticalGroup(
            BotonConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsulta3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jPanel2.add(BotonConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 310, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GAME\\Desktop\\El gordo\\Logos\\Imagen fondo.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "¡Hola Mundo!", "Esto es un título", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LabelConsulta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta1MouseEntered
        // TODO add your handling code here:
        BotonConsulta1.setBackground(Color.blue);
        LabelConsulta1.setForeground(Color.red);
    }//GEN-LAST:event_LabelConsulta1MouseEntered

    private void LabelConsulta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta1MouseExited
        // TODO add your handling code here:
        BotonConsulta1.setBackground(new Color(255, 153, 153));
        LabelConsulta1.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_LabelConsulta1MouseExited

    private void LabelConsulta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta1MouseClicked
        // TODO add your handling code here:
        ventanaLideres.setVisible(true);
    }//GEN-LAST:event_LabelConsulta1MouseClicked

    private void LabelConsulta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta2MouseEntered
        // TODO add your handling code here:
        BotonConsulta2.setBackground(Color.blue);
        LabelConsulta2.setForeground(Color.red);
    }//GEN-LAST:event_LabelConsulta2MouseEntered

    private void LabelConsulta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta2MouseExited
        // TODO add your handling code here:
        BotonConsulta2.setBackground(new Color(255, 153, 153));
        LabelConsulta2.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_LabelConsulta2MouseExited

    private void LabelConsulta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta2MouseClicked
        // TODO add your handling code here:
        ventanaMateriales.setVisible(true);
    }//GEN-LAST:event_LabelConsulta2MouseClicked

    private void LabelConsulta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta3MouseEntered
        // TODO add your handling code here:
        BotonConsulta3.setBackground(Color.blue);
        LabelConsulta3.setForeground(Color.red);
    }//GEN-LAST:event_LabelConsulta3MouseEntered

    private void LabelConsulta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta3MouseExited
        // TODO add your handling code here:
        BotonConsulta3.setBackground(new Color(255, 153, 153));
        LabelConsulta3.setForeground(new Color(0, 0, 255));
    }//GEN-LAST:event_LabelConsulta3MouseExited

    private void LabelConsulta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelConsulta3MouseClicked
        // TODO add your handling code here:
        ventanaPromedio.setVisible(true);
    }//GEN-LAST:event_LabelConsulta3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonConsulta1;
    private javax.swing.JPanel BotonConsulta2;
    private javax.swing.JPanel BotonConsulta3;
    private javax.swing.JLabel LabelConsulta1;
    private javax.swing.JLabel LabelConsulta2;
    private javax.swing.JLabel LabelConsulta3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
